# 1. Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/crisis_router
spring.datasource.username=devuser
spring.datasource.password=devpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Hibernate/JPA Settings (The "Magic" Part)
# 'update' tells Hibernate to automatically create/modify tables based on your @Entity classes
# Hibernate 6+ automatically detects the dialect from the JDBC URL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=always

# 3. PostGIS / Geometry Settings
# This ensures Spring properly handles the Point coordinates we defined
spring.main.allow-bean-definition-overriding=true

aws.s3.bucket-name=${S3_BUCKET_NAME}
aws.s3.region=us-east-1
aws.access-key=${AWS_ACCESS_KEY}

# Auth0 Config
# Auth0 Configuration
spring.security.oauth2.client.registration.auth0.client-id=${AUTH0_CLIENT_ID}
spring.security.oauth2.client.registration.auth0.client-secret=${AUTH0_CLIENT_SECRET}
spring.security.oauth2.client.registration.auth0.scope=openid,profile,email
spring.security.oauth2.client.provider.auth0.issuer-uri=https://${AUTH0_DOMAIN}/

# Map the Auth0 sub/name to the Spring Security userc
spring.security.oauth2.client.registration.auth0.client-name=Auth0
spring.security.oauth2.client.registration.auth0.client-authentication-method=client_secret_post